// Array of my work
export const portfolioItems = [
  {
    picture: '/img/piresdigital-banner.png',
    thumbnail: '/img/piresdigital-thumbnail.png',
    title: 'Pires Digital Website',
    subtitle: 'Freelance Webpage',
    copy: 'This is a website I developed for myself to use as a point of contact for freelance work. Here I use TypeScript with NextJs and Node Mailer for the contact form.',
    more: 'https://www.piresdigital.com/',
    tag: ['Next', 'Node Mailer'],
  },
  {
    picture: '/img/fbpainting-banner.png',
    thumbnail: '/img/fbpainting-thumbnail.png',
    title: 'FB Painting Website',
    subtitle: 'Webpage',
    copy: 'Developed for Fabricio, a friend from New Zealand. This website was developed using NextJs, Tailwind CSS.',
    more: 'https://fbpainting.nz/',
    tag: ['Next', 'Tailwind CSS'],
  },
  {
    picture: '/img/jdsspiffy-banner.png',
    thumbnail: '/img/jdsspiffy-thumbnail.png',
    title: 'JDS Spiffy Cleaners',
    subtitle: 'Webpage',
    copy: 'This was developed using a template.',
    more: 'https://jdsspiffycleaners.co.nz/',
    tag: ['HTML', 'CSS', 'Javascript'],
  },
  {
    picture: '/img/rps-game-banner.png',
    thumbnail: '/img/rps-game-thumbnail.png',
    title: 'Rock, Paper & Scissors Game',
    subtitle: 'Game Developed in Vanilla Js',
    copy: 'This is a simple rock, papers, scissors game developed using vanilla Javascript.',
    more: 'https://github.com/piresdigital/rock-paper-scissors',
    tag: ['Javascript'],
  },
  {
    picture: '/img/skills-network-banner.jpg',
    thumbnail: '/img/skills-network-thumbnaill.jpg',
    title: 'Django Class Platform',
    subtitle: 'Project from IBM Course',
    copy: 'This is one of the projects I developed during my IBM course. Here I designed the MySQL database tables, the front-end is very simple as the focus of this project was to design an Admin pannel using Django Admin.',
    more: 'https://github.com/piresdigital/Django-Online-Course',
    tag: ['Django', 'Database'],
  },
  {
    picture: '/img/skills-network-banner.jpg',
    thumbnail: '/img/skills-network-thumbnaill.jpg',
    title: 'Sentiment Analyzer',
    subtitle: 'Project from IBM Course',
    copy: 'This project is made up of two parts, one is a Node.Js server using the IBM Watson API, and the other is a React app receiving and rendering the data from the API.',
    more: 'https://github.com/piresdigital/Sentiment-Analyzer',
    tag: ['React', 'Node'],
  },
  {
    picture: '/img/skills-network-banner.jpg',
    thumbnail: '/img/skills-network-thumbnaill.jpg',
    title: 'Python Translator Tool',
    subtitle: 'Project from IBM Course',
    copy: "Here I developed a simple yet working text translator using the LanguageTranslatorV3 from IBM Watson and Python web server Flask. This project was to learn about API's end points and data handling.",
    more: 'https://github.com/piresdigital/IBM-Flask-Translator',
    tag: ['Python', 'Flask', 'IBM Watson'],
  },
  {
    picture: '/img/skills-network-banner.jpg',
    thumbnail: '/img/skills-network-thumbnaill.jpg',
    title: 'IBM Capstone Project',
    subtitle: 'Final Project from IBM Course',
    copy: 'This was the final project for the IBM Full-Stack Developer Course and had several steps to complete. To give you an overview of the whole project, all the high-level please click the see more link on the side. ',
    more: 'https://github.com/piresdigital/IBM-Capstone-Project',
    tag: ['Django', 'Docker', 'Server'],
  },
  {
    picture: '/img/node-app-banner.jpg',
    thumbnail: '/img/node-app-thumbnail.jpg',
    title: 'Notes App',
    subtitle: 'Node.Js Course Project',
    copy: 'Simple notes taking app used to practice what was learnt during the Node.Js Course.',
    more: 'https://github.com/piresdigital/notes-app',
    tag: ['Node.JS', 'React'],
  },
];
